//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.12 at 07:22:55 PM CET 
//


package lge.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the lge.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: lge.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Event.Options }
     * 
     */
    public Event.Options createEventOptions() {
        return new Event.Options();
    }

    /**
     * Create an instance of {@link Event.Extensions }
     * 
     */
    public Event.Extensions createEventExtensions() {
        return new Event.Extensions();
    }

    /**
     * Create an instance of {@link Event.Images }
     * 
     */
    public Event.Images createEventImages() {
        return new Event.Images();
    }

    /**
     * Create an instance of {@link Event.Texts }
     * 
     */
    public Event.Texts createEventTexts() {
        return new Event.Texts();
    }

    /**
     * Create an instance of {@link Event.Options.Option }
     * 
     */
    public Event.Options.Option createEventOptionsOption() {
        return new Event.Options.Option();
    }

    /**
     * Create an instance of {@link Event.Extensions.Extension }
     * 
     */
    public Event.Extensions.Extension createEventExtensionsExtension() {
        return new Event.Extensions.Extension();
    }

}
