package crashsite;

import lge.res.images.ImageKey;

public enum CrashSite implements ImageKey {
  IN_OWN_SEAT_IN_PLANE,
  INSIDE_FUSELAGE,
  COCKPIT,
  OUTSIDE_PLANE,
  OUTSIDE_PLANE_MORNING,
  SHELTER,
  OUTSIDE_PLANE_NON_BURNING,
  INSIDE_FUSELAGE_NON_BURNING,
  COCKPIT_NON_BURNING,
  LOOK_FOR_SURVIVORS_AFTER_CRASH,
  LOOK_FOR_MORE_SURVIVORS_AFTER_CRASH,
  DREAM_AFTER_CRASH,
  ANGRY_DISCUSSION,
  FIRST_DISCUSSION_GROUP,
  FIRST_DISCUSSION_TOPIC_1,
  FIRST_DISCUSSION_TOPIC_2,
  FIRST_DISCUSSION_TOPIC_3,
  FIRST_DISCUSSION_TOPIC_4,
  FIRST_DISCUSSION_TOPIC_5,
  FIRST_DISCUSSION_TOPIC_6,
  FIRST_DISCUSSION_TOPIC_7,
  FIRST_DISCUSSION_TOPIC_8,
}
