package org.lehirti.engine.res.text;

public enum CommonText implements TextKey {
  KEY_OPTION,
  OPTION_LEAVE,
  OPTION_NEXT,
  OPTION_PREVIOUS,
  OPTION_BACK,
  OPTION_LEAVE_HOUSE,
  OPTION_EXPLORE_AREA,
  OPTION_LEAVE_AREA,
  INVENTORY,
  DAY,
  TIME_FORMAT,
  BLANK,
  MARKER,
  OPTION_DO_IT,
  OPTION_USE_IT;
}
