//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:43:20 PM CET 
//


package lge.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for key_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="key_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Q"/>
 *     &lt;enumeration value="LEAVE"/>
 *     &lt;enumeration value="NORTH"/>
 *     &lt;enumeration value="ENTER"/>
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="WEST"/>
 *     &lt;enumeration value="SOUTH"/>
 *     &lt;enumeration value="EAST"/>
 *     &lt;enumeration value="Z"/>
 *     &lt;enumeration value="X"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="V"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "key_type")
@XmlEnum
public enum KeyType {

    Q,
    LEAVE,
    NORTH,
    ENTER,
    A,
    WEST,
    SOUTH,
    EAST,
    Z,
    X,
    C,
    V;

    public String value() {
        return name();
    }

    public static KeyType fromValue(String v) {
        return valueOf(v);
    }

}
